### ISSUE TITLE
Doesn't work with Catalina

### ISSUE THREAD

**Issue by asschweizer** [tibOin/macos_speech#1]
Hi, badly it doesn't work with my fresh Catalina environment.

Do you have any ideas?

**Comment by tibOin** [comment]
Hi ! Someone interested in my poor work ^^

Is your env. up to date (last update) ? This code is some month old and might not be anymore compatible. I’ll Check that tonight. 

Thanks for your interest!

(Did you use pip or cloned the repo ?)

**Comment by tibOin** [comment]
Oh! And which Python are you using ?

**Comment by tibOin** [comment]
Ok, I just tried it out and got import errors using python 3.8.1. There are things I still don't understand on \_\_init\_\_.py files... 

It's been solved by using 
```python
from macos_speech.macos_speech import Synthesizer
...
```

I'm documenting myself on \_\_init\_\_.py files and python package's structure and will patch it soon.
If it's not your problem please detail it.

**Comment by asschweizer** [comment]
Yeah, someone is interested in your work, but it isn't poorly ;-)

I tried your workaround but reinstalled my python (3.7.x) environment and got these message via pip:
Collecting macos_speech
  Using cached macos_speech-1.0.0.tar.gz (4.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/{interested_in_your_work_user}/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/setup.py'"'"'; __file__='"'"'/private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/pip-egg-info
         cwd: /private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/setup.py", line 13, in <module>
        long_description=readme(),
      File "/private/var/folders/jq/pbpgflm968l5p0zq686p_m6r0000gn/T/pip-install-qimsielf/macos-speech/setup.py", line 7, in readme
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

So latest python 3.7.x is struggling with Catalina, maybe it's one of those rabbit holes..

**Comment by tibOin** [comment]
Yes I've experimented it through pip... I don't understand why because the README.md exists. I have to change the packet.

Try cloning the repo and ```pip install .```. That worked for me.

**Comment by tibOin** [comment]
I modified the README.md file to take in account the workarounds. So by following it's _new_ installation procedure it should work... Hope so.

**Comment by tibOin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fermer l'issue](https://trello.com/c/5pHilgXV/4-fermer-lissue)

**Comment by tibOin** [comment]
Ok, it was... simple. A dot was missing in my \_\_init\_\_.py as Python 3 is more strict.

So everything is updated. You can now install through pip. And the import syntax is fixed.

This issue is officially closed.
